name = "Grapher"
uuid = "cb5f3ba8-f211-439d-a907-3cde74a9b555"
authors = ["Keita Nakamura <keita.nakamura.1109@gmail.com>"]
version = "0.4.3"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
MappedArrays = "dbb5928d-eab1-5f90-85c2-b9b0edb7c900"
PGFPlotsX = "8314cec4-20b6-5062-9cdb-752b83310925"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
CSV = "0.9"
LaTeXStrings = "1.2, 1.3"
MappedArrays = "0.4"
PGFPlotsX = "1.2, 1.3, 1.4"
Reexport = "1.2"
julia = "1.6"
